### PR TITLE
Dev/loganalytics

### PR DESCRIPTION
**Pull request by bdpatel1**
Intents for various log analytics use cases.
@sgajane 
@cgandhi2 
@awsjarvis1/log-analytics

### CODE REVIEW

**Review by cgandhi2 — DISMISSED** [review]

**Comment by msmatharu** [comment]
approved

**Review by msmatharu — DISMISSED** [review]
Changes look good.

**Review by cgandhi2 — DISMISSED** [review]

**Comment by awsjarvis** [comment]
test this please

**Comment by awsjarvis** [comment]
test this please

**Comment by awsjarvis** [comment]
test this please

**Comment by awsjarvis** [comment]
test this please

**Comment by awsjarvis** [comment]
tests this please

**Comment by awsjarvis** [comment]
test this please

**Comment by awsjarvis** [comment]
test this please

**Comment by awsjarvis** [comment]
test this please

**Comment by awsjarvis** [comment]
test this please

**Comment by awsjarvis** [comment]
test this code

**Comment by awsjarvis** [comment]
test this please

**Comment by awsjarvis** [comment]
test this please

**Comment by awsjarvis** [comment]
test this please

**Review by dbpatel1 — DISMISSED** [review]
Looks good

**Review by msmatharu — DISMISSED** [review]
Looks good

**Comment by bdpatel1** [comment]
test this please

**Review by msmatharu — APPROVED** [review]
Looks great

**Pull request merged**
